title: Lucas Ribeiro
description: Blog para compartilhamento de experiencias em qa, automação e engenharia de software em geral.

url: "https://lucrib.github.io/tech"
baseurl: "/tech"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: lucrib
   twitter: lucrib_
   facebook: lucrib
   email: lucasribeiro1990@gmail.com

google_analytics: "UA-85624987-1"
